I had written this test earlier, but the problem is that this function runs process.exit which 
will exit not just Bejeweled but the test as well.

it("ends the game when no valid moves are left", async function () {
      grid = [
        ["🥝", "🍓", "🥥", "🍇", "🔥", "☺️", "😚", "🧮"],
        ["✈️", "🩹", "🎟", "🧑🏼", "🚡", "🛬", "🛫", "⏰"],
        ["⚗️", "👽", "🚑", "👾", "🏺", "🏈", "🛏", "🐝"],
        ["🪲", "🧗🏼", "🍺", "🏛", "🔃", "📀", "⭐️", "✡️"],
        ["🕡", "👔", "➡️", "🫱��", "⭐️", "↙️", "🗳", "📫"],
        ["⚗️", "👽", "🚑", "👾", "🏺", "🏈", "🛏", "🐝"],
        ["🪲", "🧗🏼", "🍺", "🏛", "🔃", "📀", "⭐️", "✡️"],
        ["🕡", "👔", "➡️", "🫱🏼", "⭐️", "↙️", "🗳", "📫"],
      ];
      options = ["new"];
      await Bejeweled.checkForMatches(grid, options);
      expect(Screen.message).to.equal("No more swaps are possible. Game over.");
    });
